### ISSUE TITLE
Unable to change default comment character from semi-colon to hash

### ISSUE THREAD

**Issue by ssbarnea** [jacobbednarz/atom-language-ini#38]
It seems that is not possible (or not documented) how to change the default commend character from semi-colon ``;`` to hash ``#`` which seems to have a wider adoption/support in ini files.

This is quite annoying for those that are used to comment/uncomment blocks using the ``Cmd+/`` keyboard shortcut.

**Comment by jacobbednarz** [comment]
Hi,

I'm afraid the comment character isn't configurable. If you search back through the issues and PRs in this repository, you will see that the INI syntax has been riddled with inconsistencies between implementations and there is no standard to stick to which is extremely unfortunate and difficult to work with. 

I'm hesitant to make any changes that are related to perceived wider adoption/support since that view changes based on which systems or implementations the reporter is most familiar with. 

Happy to make some changes if there is data or supporting material to suggest this situation has changed in the last few months.
